import path from "node:path";

import { analyzeRepository } from "./analyzer.js";
import { EXIT_CODES } from "./constants.js";
import {
  ensureDirectory,
  pathExists,
  readJsonFile,
  writeJsonFile,
  writeTextFile,
} from "./utils/fs.js";

const LIFF_MOCK_VERSION = "^1.0.3";
const TOOL_SIGNATURE = "// Generated by liff-testgen. Do not edit inside autogen blocks.";
const SCAFFOLD_FILES = {
  "testing/liff/setupLiffMock.ts": buildSetupLiffMockTemplate,
  "testing/liff/fixtures.ts": buildFixturesTemplate,
  "testing/liff/applyFixture.ts": buildApplyFixtureTemplate,
  "testing/liff/resetFixture.ts": buildResetFixtureTemplate,
  "testing/liff/types.ts": buildTypesTemplate,
};

export async function prepareRepository(context, logger) {
  const { repoPath, options } = context;
  logger.info("Stage started: prepare", {
    stage: "prepare",
    repoPath,
    dryRun: options.dryRun,
  });

  const analysis = await loadOrAnalyze(context, logger);
  if (!analysis.ok) {
    return {
      stage: "prepare",
      ok: false,
      exitCode: analysis.exitCode,
      message: analysis.message,
      errorCode: analysis.errorCode,
      data: analysis.data,
    };
  }

  const { projectProfile, liffUsageReport, existingTestMap } = analysis.data;
  if (!projectProfile.usesLiff) {
    return {
      stage: "prepare",
      ok: false,
      exitCode: EXIT_CODES.UNSUPPORTED_PROJECT,
      message: "Prepare requires a LIFF repository.",
      errorCode: "LIFF_NOT_DETECTED",
      data: analysis.data,
    };
  }

  const mutations = [];
  const packageJsonPath = path.join(repoPath, "package.json");
  const packageJson = await readJsonFile(packageJsonPath);
  const updatedPackageJson = ensureLiffMockDependency(packageJson, mutations);
  const updatedProjectProfile = {
    ...projectProfile,
    hasLiffMock: true,
  };

  if (!options.dryRun && updatedPackageJson !== packageJson) {
    await writeJsonFile(packageJsonPath, updatedPackageJson);
  }

  const scaffoldMutations = await ensureScaffoldFiles(repoPath, projectProfile, options.dryRun);
  mutations.push(...scaffoldMutations);

  mutations.push({
    path: ".liff-testgen/project-profile.json",
    action: (await pathExists(path.join(repoPath, ".liff-testgen/project-profile.json"))) ? "update" : "create",
  });
  const pipelineStatePath = path.join(repoPath, ".liff-testgen/pipeline-state.json");
  mutations.push({
    path: ".liff-testgen/pipeline-state.json",
    action: (await pathExists(pipelineStatePath)) ? "update" : "create",
  });
  const pipelineState = buildPipelineState(mutations, options.dryRun);

  if (!options.dryRun) {
    const outputDir = path.join(repoPath, ".liff-testgen");
    await ensureDirectory(outputDir);
    await writeJsonFile(path.join(outputDir, "project-profile.json"), updatedProjectProfile);
    await writeJsonFile(path.join(outputDir, "pipeline-state.json"), pipelineState);
  }

  return {
    stage: "prepare",
    ok: true,
    exitCode: EXIT_CODES.SUCCESS,
    message: "Repository preparation completed.",
    data: {
      dryRun: options.dryRun,
      projectProfile: updatedProjectProfile,
      liffUsageReport,
      existingTestMap,
      mutations,
      pipelineState,
    },
  };
}

async function loadOrAnalyze(context, logger) {
  const repoPath = context.repoPath;
  const profilePath = path.join(repoPath, ".liff-testgen/project-profile.json");
  const usagePath = path.join(repoPath, ".liff-testgen/liff-usage-report.json");
  const testMapPath = path.join(repoPath, ".liff-testgen/existing-test-map.json");

  if ((await pathExists(profilePath)) && (await pathExists(usagePath)) && (await pathExists(testMapPath))) {
    return {
      ok: true,
      exitCode: EXIT_CODES.SUCCESS,
      data: {
        dryRun: context.options.dryRun,
        outputs: [
          ".liff-testgen/project-profile.json",
          ".liff-testgen/liff-usage-report.json",
          ".liff-testgen/existing-test-map.json",
        ],
        projectProfile: await readJsonFile(profilePath),
        liffUsageReport: await readJsonFile(usagePath),
        existingTestMap: await readJsonFile(testMapPath),
      },
    };
  }

  return analyzeRepository(
    context,
    logger,
  );
}

function ensureLiffMockDependency(packageJson, mutations) {
  if (hasDependency(packageJson, "@line/liff-mock")) {
    return packageJson;
  }

  const nextPackageJson = structuredClone(packageJson);
  nextPackageJson.devDependencies ??= {};
  nextPackageJson.devDependencies["@line/liff-mock"] = LIFF_MOCK_VERSION;
  nextPackageJson.devDependencies = sortObjectKeys(nextPackageJson.devDependencies);

  mutations.push({
    path: "package.json",
    action: "update",
    reason: "Added @line/liff-mock to devDependencies.",
  });

  return nextPackageJson;
}

async function ensureScaffoldFiles(repoPath, projectProfile, dryRun) {
  const mutations = [];

  for (const [relativePath, templateBuilder] of Object.entries(SCAFFOLD_FILES)) {
    const absolutePath = path.join(repoPath, relativePath);
    const nextContent = templateBuilder(projectProfile);
    const exists = await pathExists(absolutePath);

    if (!exists) {
      mutations.push({
        path: relativePath,
        action: "create",
      });

      if (!dryRun) {
        await ensureDirectory(path.dirname(absolutePath));
        await writeTextFile(absolutePath, nextContent);
      }
      continue;
    }

    const currentContent = await readTextFileSafe(absolutePath);
    if (!isToolOwned(currentContent)) {
      mutations.push({
        path: relativePath,
        action: "skip",
        reason: "Existing file is not tool-owned.",
      });
      continue;
    }

    if (currentContent === nextContent) {
      mutations.push({
        path: relativePath,
        action: "skip",
        reason: "Scaffold is already up to date.",
      });
      continue;
    }

    mutations.push({
      path: relativePath,
      action: "update",
    });

    if (!dryRun) {
      await writeTextFile(absolutePath, nextContent);
    }
  }

  return mutations;
}

async function readTextFileSafe(filePath) {
  const { readFile } = await import("node:fs/promises");
  return readFile(filePath, "utf8");
}

function isToolOwned(content) {
  return content.includes(TOOL_SIGNATURE);
}

function buildPipelineState(mutations, dryRun) {
  return {
    schemaVersion: "1",
    lastRunAt: new Date().toISOString(),
    completedStages: ["analyze", "prepare"],
    generatorVersion: "0.1.0",
    dryRun,
    fileMutations: mutations.map((mutation) => ({
      path: mutation.path,
      action: mutation.action,
    })),
  };
}

function buildSetupLiffMockTemplate() {
  return `${TOOL_SIGNATURE}
import { resetLiffFixture } from "./resetFixture";

export function setupLiffMock() {
  resetLiffFixture();
}
`;
}

function buildFixturesTemplate() {
  return `${TOOL_SIGNATURE}
import { LiffFixtureMap } from "./types";

export const liffFixtures: LiffFixtureMap = {
  loggedOut: {
    isLoggedIn: false,
    isInClient: false,
    accessToken: null,
    idToken: null,
    profile: null,
  },
  loggedIn: {
    isLoggedIn: true,
    isInClient: true,
    accessToken: "mock-access-token",
    idToken: "mock-id-token",
    profile: {
      userId: "U1234567890",
      displayName: "Mock User",
    },
  },
  profileFailed: {
    isLoggedIn: true,
    isInClient: true,
    profileError: "Failed to load profile",
  },
  tokenExpired: {
    isLoggedIn: true,
    isInClient: true,
    accessToken: null,
    idToken: null,
  },
  initFailed: {
    initError: "LIFF init failed",
  },
  notInClient: {
    isLoggedIn: true,
    isInClient: false,
  },
  permissionDenied: {
    isLoggedIn: true,
    profileError: "Permission denied",
  },
};
`;
}

function buildApplyFixtureTemplate() {
  return `${TOOL_SIGNATURE}
import { liffFixtures } from "./fixtures";
import { LiffFixtureName, LiffFixtureState, MutableLiffFixtureState } from "./types";

const currentFixtureState: MutableLiffFixtureState = {};

export function applyLiffFixture(name: LiffFixtureName, overrides = {}) {
  Object.assign(currentFixtureState, liffFixtures[name], overrides);
  return currentFixtureState;
}

export function getCurrentLiffFixture(): LiffFixtureState {
  return currentFixtureState;
}
`;
}

function buildResetFixtureTemplate() {
  return `${TOOL_SIGNATURE}
import { getCurrentLiffFixture } from "./applyFixture";

export function resetLiffFixture() {
  const fixture = getCurrentLiffFixture();
  for (const key of Object.keys(fixture)) {
    delete fixture[key];
  }
}
`;
}

function buildTypesTemplate() {
  return `${TOOL_SIGNATURE}
export interface LiffFixtureState {
  isLoggedIn?: boolean
  isInClient?: boolean
  accessToken?: string | null
  idToken?: string | null
  initError?: string | null
  profileError?: string | null
  profile?: {
    userId?: string
    displayName?: string
  } | null
}

export type MutableLiffFixtureState = Record<string, unknown> & LiffFixtureState;

export type LiffFixtureName =
  | "loggedOut"
  | "loggedIn"
  | "profileFailed"
  | "tokenExpired"
  | "initFailed"
  | "notInClient"
  | "permissionDenied";

export type LiffFixtureMap = Record<LiffFixtureName, LiffFixtureState>;
`;
}

function hasDependency(packageJson, dependencyName) {
  const collections = [
    packageJson.dependencies,
    packageJson.devDependencies,
    packageJson.peerDependencies,
    packageJson.optionalDependencies,
  ];

  return collections.some((collection) => Boolean(collection?.[dependencyName]));
}

function sortObjectKeys(input) {
  return Object.fromEntries(Object.entries(input).sort(([left], [right]) => left.localeCompare(right)));
}
